### ISSUE TITLE
print Storyboarder Worksheet" don't work 

### ISSUE THREAD

**Issue by boarderfrance** [wonderunit/storyboarder#537]
The function "print Storyboarder Worksheet" don't work on Windows 10 pro (both Surface 4 and HP Workstation). It seems there is no communication with the printers programs.

**Comment by setpixel** [comment]
I was afraid about this in windows 10. When you go to see if anything is in the printers, do you see anything?

**Comment by boarderfrance** [comment]
No, the printers lists are completely empty

**Comment by setpixel** [comment]
Thanks - I'm going to try to get windows 10 machine to figure out what's wrong. Storyboard printing is a really cool feature

**Comment by setpixel** [comment]
Can you check on the latest release? I suspect it still doesn't work. FYI, you can also now export a pdf of the worksheet to print.

**Comment by boarderfrance** [comment]
Hi Charles,

Sorry, I couldn't not use this version because of errors in loop :

the same messages always coming again after typing OK.

Benoît
[image: Images intégrées 2]

*[image: Images intégrées 3]*

2017-08-29 1:47 GMT+02:00 Charles Forman <notifications@github.com>:

**Comment by setpixel** [comment]
@boarderfrance can you take a screenshot of the error messages? that would be very helpful!

**Comment by boarderfrance** [comment]
Yes sorry
here it is

![error](https://user-images.githubusercontent.com/31380825/29834969-bcaa885e-8cf0-11e7-9f24-451e45c6a418.jpg)
![error2](https://user-images.githubusercontent.com/31380825/29834982-c348075e-8cf0-11e7-8bbd-7bd3cd9feb1e.jpg)

**Comment by boarderfrance** [comment]
It's probably because I have erase a project

**Comment by audionerd** [comment]
I think the second error is related to https://github.com/wonderunit/storyboarder/issues/544

Do you remember what setting you had in preferences for "Enable Brush Cursor While Drawing"?

**Comment by boarderfrance** [comment]
This option was off

**Comment by audionerd** [comment]
Are you able to enable the option, restart, and see if the drawing workspace loads properly?

**Comment by boarderfrance** [comment]
no

I can't access to the interface.

Is there a possibility to desinstall completely and to erase all the
preferences, the list of previous project, etc... ?

Thanks

Benoît

2017-08-29 20:18 GMT+02:00 Eric Skogen <notifications@github.com>:

**Comment by setpixel** [comment]
@boarderfrance you can delete the data inside of the storyboader appdata folder:

https://www.howtogeek.com/318177/what-is-the-appdata-folder-in-windows/

you can find storyboarder folders in there and delete everything in them.

We are also going to fix and issue a patch fix today.

**Comment by setpixel** [comment]
@boarderfrance this might help too: http://www.windows10themes.net/guides/how-to-view-the-appdata-folder-in-windows-10/

**Comment by boarderfrance** [comment]
Ok thanks,
it works now

**Comment by setpixel** [comment]
I just pushed a new version live that will allow you to import them nicely, if you'd like to try that out as well.

**Comment by boarderfrance** [comment]
Many thanks Charles.
The print button for Worksheet still not answer on windows 10,  but the possibility of a PDF is great !

**Comment by setpixel** [comment]
@boarderfrance I see that a lot of people in france are using Storyboarder. Do you think it would be helpful to support french language? Or are many people ok with english?

**Comment by boarderfrance** [comment]
Why not indeed.
If you want I can help you. if you give me a list of all the words used in the proigramm, i'll translate it for you.

**Comment by setpixel** [comment]
Moved to #555
